### ISSUE TITLE
Style Nitpicks

### ISSUE THREAD

**Issue by freddyheppell** [projectcitybuild/web#287]
A list of all the small styling issues that all need to be addressed at some point: 

- [ ] Button icon spacing
- [ ] Card padding in ems not rems so font size affects (also means card tables don't line up)
  ![Screenshot 2020-12-22 at 17 34 28](https://user-images.githubusercontent.com/1475568/102916784-05456700-447c-11eb-8976-770a70ac4258.png)
- [ ] Background image behaves much better on forums when window height shrunk
- [ ] Sidemenu active clashes with sidemenu border
  <img width="585" alt="image" src="https://user-images.githubusercontent.com/1475568/102994735-89006180-4517-11eb-96cc-8306089b69d5.png">

**Comment by andyksaw** [comment]
Closing since we're using a new design now
