### ISSUE TITLE
Support API versioning

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/web#288]
We'll eventually want to introduce some breaking changes to our APIs, and we need versioning to maintain backwards compatibility with PCBridge

**Comment by freddyheppell** [comment]
It would be nice if we did implementation testing of the API, that is wrote tests which exactly compare respones to some JSON file on disk. This makes it impossible to change the API without it flagging up. It also means we have accurate examples of what each API returns.

**Comment by freddyheppell** [comment]
Also, if we're overhauling the API anyway I think we should switch our API auth to [Laravel Passport](https://laravel.com/docs/8.x/passport). We can remove our own API key implementation for servers and also use it for other SSO we might want to do (e.g. the wiki), and do automatic transient key generation for SPAs.
