### ISSUE TITLE
Automatically fix linter issues

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/web#314]
We could add a `pre-commit` git hook to run the linter fix command, but that would drastically increase the time required to commit because the linter checks every repository file instead of just modified files

**Comment by freddyheppell** [comment]
I'm wondering if it might be worth migrating to [StyleCI](https://styleci.io/). It's what Laravel itself uses for style checking and it's free for open source projects. It adds itself as a PR check so it's much easier to spot PRs that introduce style errors and seems to support much better auto fixing.
