### ISSUE TITLE
Not redirected to panel after logging in

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/web#594]
**Describe the bug**

Attempting to access the panel without logging in takes you to the login page - however, after logging in successfully you're redirected to the account setting page instead of the panel

**Comment by freddyheppell** [comment]
I think this will be a middleware order issue - the middleware checks that the (nonexistent) authenticated user has MFA, which it does not, redirects to the account settings page, then the auth middleware redirects to login.
