### ISSUE TITLE
Aliases not eager loaded with `Activity` model

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/web#703]
**Describe the bug**
Aliases are not eager loaded with `Activity` models in the panel.

This is causing very slow lookup speeds in production

<img width="1728" alt="Screen Shot 2022-09-22 at 15 41 47" src="https://user-images.githubusercontent.com/7236312/191676490-fb62f2fc-0637-4585-9bc6-0398928018b7.png">

**Comment by andyksaw** [comment]
I haven't looked into it at all yet, so I'm not sure if this is an implementation issue or a technical limitation of the auditing library

**Comment by freddyheppell** [comment]
We do eager load the model which was changed, but I think this happens because when we show the model name of a Minecraft player is gets the most recent alias. Not sure if there's a way to conditionally load this relationship?
